name: Monitor Shiro push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # 每5分钟运行一次
  workflow_dispatch:

permissions:
  contents: write

env:
  HASH_FILE: build_hash

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Read existing HASH_FILE content
        id: read_hash
        run: |
          content=$(cat ${{ env.HASH_FILE }}) || true
          echo "hash_content=$content" >> "$GITHUB_OUTPUT"

      - name: Get latest commit hash from Shiro repository
        id: get_latest_hash
        run: |
          latest_hash=$(git ls-remote https://github.com/Ssttar/TechTrek.git HEAD | awk '{ print $1 }')
          echo "latest_hash=$latest_hash" >> "$GITHUB_OUTPUT"

      - name: Compare hashes
        id: hash_compare
        env:
          LATEST_HASH: ${{ steps.get_latest_hash.outputs.latest_hash }}
          CURRENT_HASH: ${{ steps.read_hash.outputs.hash_content }}
        run: |
          if [ "$LATEST_HASH" != "$CURRENT_HASH" ]; then
            echo "hash_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "hash_changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Trigger workflow in Another Repository
        if: steps.hash_compare.outputs.hash_changed == 'true'
        run: |
          # Set the required variables
          repo_owner="Ssttar"
          repo_name="Shiroi"
          event_type="tigger-workflow"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d '{"event_type": "'"$event_type"'", "client_payload": {"ref": "'"$LATEST_HASH"'"}}'

      - name: Write hash to file
        if: steps.hash_compare.outputs.hash_changed == 'true'
        env:
          LATEST_HASH: ${{ steps.get_latest_hash.outputs.latest_hash }}
        run: echo $LATEST_HASH > ${{ env.HASH_FILE }}

      - name: Commit files
        if: steps.hash_compare.outputs.hash_changed == 'true'
        run: |
          git config --local user.email "bot@ssstttar.com"
          git config --local user.name "Star_bot"
          git add ${{ env.HASH_FILE }}
          git commit -a -m "Update hash file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
