name: Monitor Shiro push

on:
  schedule:
    - cron: '*/5 * * * *' # 每5分钟运行一次
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Check for new commits in Shiro
        run: |
          last_commit_sha=$(curl -s https://api.github.com/repos/innei-dev/Shiroi/commits | jq -r '.[0].sha')
          echo "SHA=$last_commit_sha" >> $GITHUB_ENV

      - name: Trigger workflow in Another Repository
        if: env.SHA != ''
        run: |
          #Set the required variables
          repo_owner="Ssttar"
          repo_name="Shiroi"
          event_type="tigger-workflow"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d '{"event_type": "'"$event_type"'", "client_payload": {"ref": "'"$SHA"'"}}'

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Write hash to file
        env:
          SHA: ${{ env.SHA }}
        run: echo $SHA > build_hash

      - name: Commit files
        run: |
          git config --local user.email "bot@ssstttar.com"
          git config --local user.name "Star_bot"
          git add build_hash
          git commit -a -m "Update hash file"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
