name: Monitor Shiro push

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  HASH_FILE: build_hash

jobs:
  check_hash:
    name: Check Hash
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message != 'Update hash file' }}
    outputs:
      hash_changed: ${{ steps.hash_compare.outputs.hash_changed }}
      latest_hash: ${{ steps.get_latest_hash.outputs.latest_hash }}

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Read existing HASH_FILE content
        id: read_hash
        run: |
          if [ -f ${{ env.HASH_FILE }} ]; then
            content=$(cat ${{ env.HASH_FILE }})
          else
            content=""
          fi
          echo "hash_content=$content" >> "$GITHUB_ENV"
          echo "hash_content=$content" >> "$GITHUB_OUTPUT"

      - name: Get latest commit hash from Shiro repository
        id: get_latest_hash
        run: |
          latest_hash=$(git ls-remote https://github.com/innei-dev/Shiroi.git HEAD | awk '{ print $1 }')
          echo "latest_hash=$latest_hash" >> "$GITHUB_OUTPUT"

      - name: Compare hashes
        id: hash_compare
        env:
          LATEST_HASH: ${{ steps.get_latest_hash.outputs.latest_hash }}
          CURRENT_HASH: ${{ steps.read_hash.outputs.hash_content }}
        run: |
          echo "CURRENT_HASH=${{ env.CURRENT_HASH }}"
          echo "LATEST_HASH=${{ env.LATEST_HASH }}"
          if [ "${{ env.LATEST_HASH }}" != "${{ env.CURRENT_HASH }}" ]; then
            echo "hash_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "hash_changed=false" >> "$GITHUB_OUTPUT"
          fi
          echo "latest_hash=${{ env.LATEST_HASH }}" >> "$GITHUB_OUTPUT"

  monitor:
    name: Monitor and Execute
    needs: check_hash
    runs-on: ubuntu-latest
    if: needs.check_hash.outputs.hash_changed == 'true'
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Trigger workflow in Another Repository
        run: |
          repo_owner="Ssttar"
          repo_name="Shiroi"
          event_type="trigger-workflow"

          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
          -d '{"event_type": "$event_type", "client_payload": {}}'

      - name: Write hash to file
        env:
          LATEST_HASH: ${{ needs.check_hash.outputs.latest_hash }}
        run: echo $LATEST_HASH > ${{ env.HASH_FILE }}

      - name: Commit files
        run: |
          git config --local user.email "bot@ssstttar.com"
          git config --local user.name "Star_bot"
          git add ${{ env.HASH_FILE }}
          git commit -m "Update hash file to ${{ needs.check_hash.outputs.latest_hash }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
